name: PMD Code Analysis

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  security-events: write
  actions: write

jobs:
  pmd:
    name: Run PMD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run PMD
        uses: pmd/pmd-github-action@d9c1f3c5940cbf5923f1354e83fa858b4496ebaa
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
          analyzeModifiedFilesOnly: false

      - name: Upload PMD report
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0
        with:
          sarif_file: pmd-report.sarif

      - name: "Upload artifact"
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: sarif-file
          path: pmd-report.sarif
          retention-days: 5