name: PMD Code Analysis

on:
  push:
    branches:
      - '*'

permissions:
  contents: read
  security-events: write
  actions: write

jobs:
  pmd:
    name: Run PMD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run PMD
        uses: pmd/pmd-github-action@v1
        with:
          version: '7.0.0-rc4'
          sourcePath: 'src/'
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false

      - name: Upload PMD artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: pmd-report.sarif
          retention-days: 5